Added Ability to automatically send notification when a post is created
the-hit-times/The-HIT-Times-App-Flutter pull request #3
Opened 2023-03-03 16:39 UTC by a2krocks

2023-03-04 04:01 UTC, Ayan-10 commented
@a2krocks Provide a little description of what you did in this PR and why you did.

Thanks.

2023-03-06 11:04 UTC, Ayan-10 requested changes

2023-03-06 11:04 UTC, Ayan-10 commented on lib/notification_service/notification_service.dart
> +
Before starting each function, add some comments regarding what you have done inside that function.

2023-03-06 11:04 UTC, Ayan-10 commented on lib/homepage.dart
> +    // String imageUri = "https://scontent-del1-1.cdninstagram.com/v/t51.2885-15/333940738_737738278003133_5896829832535104130_n.webp?stp=dst-jpg_e35_s480x480&_nc_ht=scontent-del1-1.cdninstagram.com&
Remove this comment.

2023-03-06 11:22 UTC, a2krocks commented on lib/homepage.dart
> +    // String imageUri = "https://scontent-del1-1.cdninstagram.com/v/t51.2885-15/333940738_737738278003133_5896829832535104130_n.webp?stp=dst-jpg_e35_s480x480&_nc_ht=scontent-del1-1.cdninstagram.com&
Check it now

2023-03-06 12:07 UTC, Ayan-10 approved these changes

2023-03-06 12:08 UTC, merged